### ISSUE TITLE
Организация принтерной

### ISSUE THREAD

**Issue by Linka1386** [hackerembassy/space#12]
В связи с увеличением количества принтеров,  типов пластиков и работ, есть предложение переорганизовать желтый домик.

Я вижу несколько этапов работ:

- [ ]   **Герметизация (частичная) помещения**
- * [ ] окна (гибкое стекло)
- * [ ] дверной проем (рольставня)
- * [ ] продление до потолка стен (из гипсокартона (бригадой) или каркасным методом из бруса и пленки (самостоятельно))

- [ ] **Проектирование, сборка стеллажа/верстака**
- * [ ] проектирование стеллажа, расчет материала, крепежа
- * [ ] закупка пиломатериала, крепежа
- * [ ] распил, сборка стеллажа
- * [ ] установка орг.стекла/гибкого стекла по периметру полки с 3д-принтерами
- * [ ] установка направляющей для съемной передней дверки из орг.стекла для обслуживания принтеров
- * [ ] проводка электрики в столе, монтаж освещения/подсветки принтеров
- * [ ] организация хранения/подачи/сушки филамента с верхней полки

- [ ] **Проектирование, изготовление, монтаж системы вентиляции**
- * [ ] установка принудительной вытяжки
- * [ ] монтаж из ПВХ-трубы д120 горизонтальный вывод между выходным отверстием и стеной в основное помещение с 4 отводами вниз для организации автономных точек забора воздуха
- * [ ] установка в верхнюю полку отсечных клапанов/вентиляторов (?) над посадочными местами принтеров (3 шт.)
- * [ ] Сборка/установка купола над верстаком (?)
- * [ ] монтаж гофры к клапанам/вентиляторам и куполу

Готова дописать/исключить пункты, обговорить конструкцию.

**Comment by tectonick** [comment]
Принтерная теперь наверху, для ее улучшений лучше использовать новую issue
