### ISSUE TITLE
Стеллажи для хранения всех коробочек

### ISSUE THREAD

**Issue by Linka1386** [hackerembassy/space#13]
Большую часть работ по сборке стеллажа произвели. Сейчас стоят следующие задачи: 

- [ ] произвести ревизию расходников, перекомпоновать, чтобы можно было тегировать органайзеры
- [ ] закупить контейнеры/органайзеры для упорядоченного хранения
- [ ] создать карту хранения
- [ ] закрепить полки у уголкам (по 2 самореза в уголки по передней кромке каждой полки (саморезы есть))

**Comment by tort32** [comment]
Не хватает еще органайзеров под запчасти и инструмент и полок для них, для быстрого доступа

**Comment by Arcturuss** [comment]
предлагаю 2 варианта.
1) готовые органайзеры-кассетницы https://www.ozon.ru/product/sistema-hraneniya-organayzer-s-vydvizhnymi-yacheykami-gamma-chernyy-273929233/?avtc=1&avte=2&avts=1692274957&sh=moxG6HrCbA&reviewsVariantMode=2

еще вариант модульных ящиков побольше https://www.ozon.ru/product/boks-universalnyy-idea-sredniy-organayzer-dlya-hraneniya-4-sektsii-948579092

2) напечатать шкафчики-органайзеры https://www.thingiverse.com/thing:3873672

печатные могут быть более удобными и подходящими по месту, но готовые - быстрее.
я начал печатать мелкие варианты ящичков для проверки, как оно вообще будет работать.
