### ISSUE TITLE
Дизайн музыкальной комнаты

### ISSUE THREAD

**Issue by Linka1386** [hackerembassy/space#14]
- [ ] Спроектировать/купить/смонтировать подсветку с выключателем (светодиодную ленту)
- [ ] Организовать управление подсветкой в зависимости от сценария (музыка/кино/караоке) https://github.com/hackerembassy/space/issues/7
- [ ] Купить телевизор/монитор на стену
- [ ] Повесить колонки. (Удлинить провода, если понадобится)
- [ ] Купить ковролин на стену (?)
- [ ] Сделать поролоновые глушилки, закрепить
- [ ] Сделать дверь (конструкцию надо обсудить)
- [ ] Купить диско шар для антуражности 😂 💃🕺(опционально)

_Originally posted by @Linka1386 in https://github.com/hackerembassy/space/discussions/1#discussioncomment-4564266_

**Comment by tort32** [comment]
Кинотеатр Гарри-Поттера превратился в принтерную
