### ISSUE TITLE
Сломанный выключатель блока питания 3Д-принтера

### ISSUE THREAD

**Issue by Assargadon** [hackerembassy/space#5]
У блока питания 3Д-принтера сломался выключатель. Не выключает. Пока выключаем выдёргиванием кабеля. Это довольно неудобно, да и разболтается, небось, скоро.

Последовательность починки, как я её понимаю, примерно такая:
- [ ] разобрав блок питания, извлечь из него выключатель, закоротив его выводы, и собрать обратно (так принтер можно будет продолжить эксплуатировать в текущем режиме).
- [ ] используя извлечённый выключатель в качестве образца, купить выключатель на замену (можно даже несколько - выключатели всё равно нужны, почему бы и не такие?). В крайнем случае можно купить какой-нибудь не совсем такой, но рассчитанный на то, что можно будет напечатать адаптер-переходник, чтоб вставить в имеющееся гнездо.
- [ ] Имея на руках выключатель - заменить его в блоке питания.

**Comment by tort32** [comment]
Я пофиксила замыкание, кнопочка там вот такая (как на ATX PSU)
![image](https://user-images.githubusercontent.com/2276611/210208314-f9d1e420-de16-49e2-a613-9326a6920065.png)

Габариты корпуса 20x15x15мм (общая высота вместе с кнопкой и контактами - 27 мм)
![image](https://user-images.githubusercontent.com/2276611/210208849-3b298d36-860f-4403-8565-556efb718f4d.png)
Точного названия переключателя не знаю, всегда доставались из сломанных блоков питания 😄

**Comment by tort32** [comment]
https://static.chipdip.ru/lib/588/DOC016588775.jpg
https://static.chipdip.ru/lib/955/DOC002955067.pdf

**Comment by tort32** [comment]
Поставили пока размыкатель 
https://t.me/hacker_embassy/10957

**Comment by tectonick** [comment]
@Assargadon Текущий выключатель как бы работает, хоть и искрит на 220 вольт. Преддагаю пока закрыть тикет и при необходимости/желании создать тикет на замену.

**Comment by tort32** [comment]
Заменили контактором и поворотным выключателем
