### ISSUE TITLE
Организовать бухгалтерию

### ISSUE THREAD

**Issue by tectonick** [hackerembassy/space#8]
Обсуждалось предложение систематизировать бухгалтерию спейса, а именно:
- [x] Способы учета и шаринга информации о статусе сборов на различные проекты/покупки внутри от принтера до банальной аренды. Есть существующие платформы для этого вроде кикстартера и его аналогов, но они все берут приличные комиссии.
- [x] Выбрать бухгалтера (сейчас фактически этим занимается @tort32).
- [x] Организовать счета/криптокошелки и прочие средства для упрощения донатов в спейс. 

Чем проще донатить - тем больше вероятность, что люди будут это делать

**Comment by tectonick** [comment]
Для первой задачи начал писать телеграм бот

**Comment by tectonick** [comment]
Бот задеплоен
https://github.com/hackerembassy/hackerembassy-tg-bot

**Comment by tectonick** [comment]
- Криптокошельки BTC, EHT. USDT, USDC готовы и добавлены в бота
- @Assargadon в процессе получения информации об эквайринге и приеме банковских платежей

**Comment by Linka1386** [comment]
Добавлен новый бухгалтер @Linka1386.
Она может принимать деньги на актуальные сборы, т.к. чаще всех находится в спейсе.

**Comment by Linka1386** [comment]
В связи с тем, что стало 4 человека с правами бухгалтера (потенциально, нужен еще @Assargadon, принимающий безнал), появляется необходимость отслеживать кто и сколько принял + транзакции собранных средств.

To Do
- [ ] привязать в боте к получившему деньги бухгалтеру
- [ ] возможность передачи этой привязки
- [ ] добавить команду "потрачено/оплачено" (с указанием на что)
